Updated for 1.1.0.6: configure now checks for aspell.h

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2235,7 +2235,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=xmlcopyeditor
- VERSION=1.1.0.5
+ VERSION=1.1.0.6
 
 
 cat >>confdefs.h <<_ACEOF
@@ -19474,6 +19474,142 @@ if test $ac_cv_header_pcre_h = yes; then
 else
   { { echo "$as_me:$LINENO: error: PCRE headers not found" >&5
 echo "$as_me: error: PCRE headers not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+# Check ASPELL is available
+if test "${ac_cv_header_aspell_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for aspell.h" >&5
+echo $ECHO_N "checking for aspell.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_aspell_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_aspell_h" >&5
+echo "${ECHO_T}$ac_cv_header_aspell_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking aspell.h usability" >&5
+echo $ECHO_N "checking aspell.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <aspell.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking aspell.h presence" >&5
+echo $ECHO_N "checking aspell.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <aspell.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: aspell.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: aspell.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: aspell.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: aspell.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: aspell.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: aspell.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: aspell.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: aspell.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: aspell.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: aspell.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: aspell.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: aspell.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: aspell.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: aspell.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: aspell.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: aspell.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for aspell.h" >&5
+echo $ECHO_N "checking for aspell.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_aspell_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_aspell_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_aspell_h" >&5
+echo "${ECHO_T}$ac_cv_header_aspell_h" >&6; }
+
+fi
+if test $ac_cv_header_aspell_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: Aspell headers not found" >&5
+echo "$as_me: error: Aspell headers not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
